name: Java to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # ✅ Only this is required

      - name: Compile Java Code
        run: javac src/Student.java

      - name: Run Java to generate HTML
        run: echo -e "John\nAI Attendance System" | java -cp src Student

      - name: Upload to GitHub Pages branch
        run: |
          mkdir public
          cp index.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          distribution: 'default'  # ✅ Required here only

